workflows:
  react-native-android-debug:
    name: React Native Android Debug Build
    max_build_duration: 60  # Set max duration to 1 hour
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.moviebuzz"
      node: 16  # Use Node.js 16 (adjust if needed)
      java: 17  # Java 17 for Gradle compatibility

    cache:
      cache_paths:
        - ~/.gradle
        - ~/.m2
        - node_modules
        - android/.gradle
        - android/app/build

    scripts:
      - name: Install dependencies
          script: | 
      npm install
  - name: Set Android SDK location
    script: | 
      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
  - name: Build Android release
    script: | 
      cd android
      ./gradlew assembleRelease


    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

    publishing:
      email:
        recipients:
          - lijin.p@hubspire.com
      scripts:
        - name: Share build link
          script: |
            echo "Build available at: $CM_PUBLIC_LINK"
