workflows:
  react-native-android-debug:
    name: React Native Android Debug Build
    max_build_duration: 60  # Set max duration to 1 hour
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.moviebuzz"
      node: 16  # Use Node.js 16 (adjust if needed)
      java: 17  # Java 17 for Gradle compatibility
      cache:
        cache_paths:
          - ~/.gradle
          - ~/.m2
          - node_modules
          - android/.gradle
          - android/app/build

    scripts:
      - name: Install dependencies
        script: |
          rm -rf node_modules
          npm install
          npx pod-install  # For iOS, no effect on Android but ensures consistency

      - name: Verify dependencies
        script: |
          ls -la node_modules/@react-native/gradle-plugin || echo "Gradle plugin missing!"

      - name: Clean project
        script: |
          cd android
          ./gradlew clean

      - name: Reinstall Gradle Dependencies
        script: |
          cd android
          ./gradlew --refresh-dependencies

      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug --stacktrace --info

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

    publishing:
      email:
        recipients:
                     - deepak.t@hubspire.com
            - lijin.p@hubspire.com
      scripts:
        - name: Share build link
          script: |
            echo "Build available at: $CM_PUBLIC_LINK"
