workflows:
  react-native-android-debug:
    name: React Native Android Debug Build
    max_build_duration: 60  # Set max duration to 1 hour
    environment:
      vars:
        PACKAGE_NAME: "com.moviebuzz"
  
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace --info

artifacts:
  - android/app/build/outputs/apk/release/app-release.apk

    publishing:
      email:
        recipients:
          - lijin.p@hubspire.com
          - deepak.t@hubspire.com
      scripts:
        - name: Share build link
          script: |
            echo "Build available at: $CM_PUBLIC_LINK"
